Ведьма чувствует, что проникновение врагов в замок будет совсем скоро, и посылает помощницу разбудить героиню, что бы та собрала вещи и безопасно выбралась из замка.

Точкой после которой меняется весь сюжет -- героиня спешит повидаться с родителями перед побегом, но видит сцену как придворные убивают их в тронном зале. С этого момента начинается вторая часть, связанная с бегством.

До роковой точки она имеет доступ ко всему замку и получает информацию о том как в последующем надо будет сбегать.  Во время поиска вещей и осмотра локаций, мы будем лучше знакомится с людьми которые работали во дворе, будем лучше понимать их психологию и за счет этого использовать правильные приемы на них. 

Помощница ведьмы похожа на наследницу, и существует механизм меняться с ней одеждой, что бы можно быть простолюдинкой, или переодеться в предворную даму в зависимости от цели.

* MVP
1. Не нужно заморачиваться со всякими механиками времени, вместительности, модификаторами, атаками и прочим.  Весь геймплей -- у нас есть инвентарь, какая-то одеждка.
